Update Bamboo agent workflow to remove SNS notification

diff --git a/.github/workflows/ephemeral-bamboo-agent-ecr.yml b/.github/workflows/ephemeral-bamboo-agent-ecr.yml
--- a/.github/workflows/ephemeral-bamboo-agent-ecr.yml
+++ b/.github/workflows/ephemeral-bamboo-agent-ecr.yml
@@ -57,17 +57,20 @@ jobs:
     - name: Download Bamboo packages setup script from S3
       run: aws s3 cp s3://bamboo-jdks-resources/shell_scripts/install_bamboo_packages_ephemeral.sh install_bamboo_packages_ephemeral.sh
 
-    - name: Send SNS notification and exit if no changes
-      if: steps.compare.outputs.changed == 'false'
-      run: |
-        aws sns publish \
-          --topic-arn "${SNS_TOPIC_ARN}" \
-          --message "[Bamboo Docker Build] No changes detected in upstream Dockerfile. No build or push required. Image remains unchanged." \
-          --region us-west-2
-        echo "Nothing changed from previous build. Exiting workflow."
-        exit 0
-      env:
-        SNS_TOPIC_ARN: ${{ env.SNS_TOPIC_ARN }}
+    - name: Download bamboo-update-capability.sh from S3
+      run: aws s3 cp s3://bamboo-jdks-resources/shell_scripts/bamboo-update-capability.sh bamboo-update-capability.sh
+
+   # - name: Send SNS notification and exit if no changes
+   #   if: steps.compare.outputs.changed == 'false'
+   #   run: |
+   #     aws sns publish \
+   #       --topic-arn "${SNS_TOPIC_ARN}" \
+   #       --message "[Bamboo Docker Build] No changes detected in upstream Dockerfile. No build or push required. Image remains unchanged." \
+   #       --region us-west-2
+   #     echo "Nothing changed from previous build. Exiting workflow."
+   #     exit 0
+   #   env:
+   #     SNS_TOPIC_ARN: ${{ env.SNS_TOPIC_ARN }}
 
     # Proceed only if changes detected
     - name: Replace upstream Dockerfile with Amazon Linux version
@@ -102,8 +105,10 @@ jobs:
              shared-components/image/entrypoint_helpers.py  /
         COPY shared-components/support                      /opt/atlassian/support
         COPY config/*                                       /opt/atlassian/etc/
-        COPY s3-resources /s3-resources
+        COPY s3-resources/ /opt/
         COPY install_bamboo_packages_ephemeral.sh /install_bamboo_packages_ephemeral.sh
+        COPY bamboo-update-capability.sh /
+        COPY entrypoint-wrapper.sh /entrypoint-wrapper.sh
 
         RUN yum update -y && \
             yum upgrade -y && \
@@ -141,8 +146,6 @@ jobs:
         ARG DOWNLOAD_USERNAME
         ARG DOWNLOAD_PASSWORD
 
-        COPY bamboo-update-capability.sh /
-
         RUN groupadd --gid ${RUN_GID} ${RUN_GROUP} \
             && useradd --uid ${RUN_UID} --gid ${RUN_GID} --home-dir ${BAMBOO_AGENT_HOME} --shell /bin/bash ${RUN_USER} \
             && echo PATH=$PATH > /etc/environment \
@@ -157,23 +160,19 @@ jobs:
             && mkdir -p ${BAMBOO_AGENT_HOME}/conf ${BAMBOO_AGENT_HOME}/bin \
             && export TEMP_VERSION=${JAVA_VERSION#*-} && export JAVA_MAJOR_VERSION=${TEMP_VERSION%%.*} \
             && export TEMP_VERSION=${TEMP_VERSION#*.} && JAVA_MINOR_VERSION=${TEMP_VERSION%%.*} \
-            && chmod +x /bamboo-update-capability.sh && \
-               /bamboo-update-capability.sh "JDK" ${JAVA_HOME}/bin/java && \
-               /bamboo-update-capability.sh "system.jdk.JDK ${JAVA_MAJOR_VERSION}" ${JAVA_HOME}/bin/java && \
-               /bamboo-update-capability.sh "system.jdk.JDK ${JAVA_MAJOR_VERSION}.${JAVA_MINOR_VERSION}" ${JAVA_HOME}/bin/java && \
-               /bamboo-update-capability.sh "JDK ${JAVA_VERSION}" ${JAVA_HOME}/bin/java && \
-               /bamboo-update-capability.sh "Python" /usr/bin/python3 && \
-               /bamboo-update-capability.sh "Python 3" /usr/bin/python3 && \
-               /bamboo-update-capability.sh "Git" /usr/bin/git \
-            && chown -R ${RUN_USER}:root ${BAMBOO_AGENT_HOME} \
-            && chmod -R 770 ${BAMBOO_AGENT_HOME} \
-            && for file in "/opt/atlassian/support /entrypoint.py /entrypoint_helpers.py /probe-common.sh /probe-startup.sh /probe-readiness.sh /pre-launch.sh /bamboo-update-capability.sh"; do \
-               chmod -R "u=rwX,g=rX,o=rX" ${file} && chown -R root ${file}; done \
-            && chmod +x /pre-launch.sh \
-            && chmod +x /entrypoint.py
+            && chmod +x /bamboo-update-capability.sh
 
-        CMD ["/usr/local/bin/tini", "--", "/entrypoint.py"]
+        CMD ["/usr/local/bin/tini", "--", "/entrypoint-wrapper.sh"]
         ENTRYPOINT ["/pre-launch.sh"]
+        EOF
+
+    - name: Create entrypoint-wrapper.sh
+      if: steps.compare.outputs.changed == 'true'
+      run: |
+        cat <<'EOF' > entrypoint-wrapper.sh
+        #!/bin/bash
+        /bamboo-update-capability.sh || echo "Warning: bamboo-update-capability.sh failed"
+        exec /entrypoint.py
         EOF
 
     - name: Copy everything from agent-base to workspace
