Add directory copy and verification step in workflow

diff --git a/.github/workflows/ephemeral-bamboo-agent-ecr.yml b/.github/workflows/ephemeral-bamboo-agent-ecr.yml
--- a/.github/workflows/ephemeral-bamboo-agent-ecr.yml
+++ b/.github/workflows/ephemeral-bamboo-agent-ecr.yml
@@ -68,6 +68,25 @@ jobs:
     - name: Download Bamboo packages setup script from S3
       run: aws s3 cp s3://bamboo-jdks-resources/shell_scripts/install_bamboo_packages_ephemeral.sh install_bamboo_packages_ephemeral.sh
 
+    - name: Copy only directories and verify
+      run: |
+        mkdir -p s3-resources-dirs
+        for dir in s3-resources/*/; do
+          cp -r "$dir" s3-resources-dirs/
+        done
+    
+        # List directories in source and destination
+        find s3-resources -mindepth 1 -maxdepth 1 -type d | sort > /tmp/original_dirs.txt
+        find s3-resources-dirs -mindepth 1 -maxdepth 1 -type d | sort > /tmp/copied_dirs.txt
+    
+        # Compare the lists; fail the job if not identical
+        if ! diff /tmp/original_dirs.txt /tmp/copied_dirs.txt; then
+          echo "ERROR: Not all directories were copied successfully!"
+          exit 1
+        else
+          echo "All directories were copied successfully."
+        fi
+
     - name: Send SNS notification and exit if no changes
       if: steps.compare.outputs.changed == 'false'
       run: |
@@ -113,7 +132,8 @@ jobs:
              shared-components/image/entrypoint_helpers.py  /
         COPY shared-components/support                      /opt/atlassian/support
         COPY config/*                                       /opt/atlassian/etc/
-        COPY s3-resources/*                                 /opt/
+        COPY s3-resources-dirs/*                            /opt/
+        COPY s3-resources/logstream_metrics_to_cloudwatch.sh                          /opt/logstream_metrics_to_cloudwatch.sh
         COPY install_bamboo_packages_ephemeral.sh /install_bamboo_packages_ephemeral.sh
         RUN chmod +x /install_bamboo_packages_ephemeral.sh && /install_bamboo_packages_ephemeral.sh
 
