Update git_branch_rename.yml

diff --git a/.github/workflows/git_branch_rename.yml b/.github/workflows/git_branch_rename.yml
--- a/.github/workflows/git_branch_rename.yml
+++ b/.github/workflows/git_branch_rename.yml
@@ -13,11 +13,28 @@ on:
         description: NEW_BRANCH_NAME
         
 jobs:
+  Check-Repository-type_And_Branch-Name:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check if Repository type is valid
+        run: |
+          if [ "${{ inputs.OWNER }}" != "client" ] && [ "${{ inputs.OWNER }}" != "product" ]; then
+            echo "Invalid Repository type value. Stopping the workflow."
+            exit 1
+          fi
+      - name: Check if its a default branch
+        run: |
+          if [ "${{ inputs.EXISTING_BRANCH_NAME }}" = "main" ]; then
+            echo "Default branch (main) cannat be changed. Stopping the workflow."
+            exit 1
+          fi
+          
   Check-Branch-Existence:
     runs-on: ubuntu-latest
     permissions:
       id-token: write
       contents: read
+    needs: Check-Repository-type_And_Branch-Name
     steps:
     - name: Check if Branch Exists
       run: |
