Update Jira_Patching.yml

diff --git a/.github/workflows/Jira_Patching.yml b/.github/workflows/Jira_Patching.yml
--- a/.github/workflows/Jira_Patching.yml
+++ b/.github/workflows/Jira_Patching.yml
@@ -105,17 +105,20 @@ jobs:
             --auto-scaling-group-name "${{ env.ASG_NAME }}" \
             --min-size 1  
 
-      - name: Patch Instance 1
-        id: patch-instance-1
+      - name: Patch Each Instance
+        id: patch-each-instance
         run: |
           INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
-          INSTANCE_TO_PATCH=${INSTANCE_IDS_ARRAY[0]}
-          echo "Patching instance: $INSTANCE_TO_PATCH"
+          PATCH_SUCCESS=true  
 
-          aws autoscaling enter-standby \
-            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --should-decrement-desired-capacity
+          for INSTANCE_ID in "${INSTANCE_IDS_ARRAY[@]}"
+          do
+            echo "Patching instance: $INSTANCE_ID"
+
+            aws autoscaling enter-standby \
+              --auto-scaling-group-name "${{ env.ASG_NAME }}" \
+              --instance-ids "$INSTANCE_ID" \
+              --should-decrement-desired-capacity
 
           aws ssm send-command \
             --instance-ids "$INSTANCE_TO_PATCH" \
@@ -123,132 +126,122 @@ jobs:
             --comment "Stop Jira and HTTPD services" \
             --parameters 'commands=["sudo service httpd stop", "sudo service jira stop"]'
 
-          aws ssm send-command \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Upgrade to latest Amazon Linux release" \
-            --parameters 'commands=["dnf -y --releasever=latest update"]'
+            aws ssm send-command \
+              --instance-ids "$INSTANCE_ID" \
+              --document-name "AWS-RunShellScript" \
+              --comment "Upgrade to latest Amazon Linux release" \
+              --parameters 'commands=["dnf -y --releasever=latest update"]' \
+              --query 'Command.CommandId' --output text > command-id.txt
+              COMMAND_ID=$(cat command-id.txt)
+              echo "Waiting for upgrade command to complete..."
+              for i in {1..30}; do
+                  COMMAND_STATUS=$(aws ssm list-commands --command-id "$COMMAND_ID" --query 'Commands[0].Status' --output text)
+                  echo "Current command status: $COMMAND_STATUS"     
+                  if [[ "$COMMAND_STATUS" == "Success" ]]; then
+                      echo "Command completed successfully."
+                      break
+                  elif [[ "$COMMAND_STATUS" == "Failed" ]]; then
+                      echo "Command failed. Exiting..."
+                      exit 1
+                  fi
+                  sleep 30  
+              done              
+              if [[ "$COMMAND_STATUS" != "Success" ]]; then
+                  echo "Max attempts exceeded. Command did not complete."
+                  exit 1
+              fi
 
-          aws ssm send-command \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Reboot EC2 instance" \
-            --parameters 'commands=["sudo reboot"]'
-                          
-          sleep 120
+            echo "Stop the instance"
+            aws ec2 stop-instances --instance-ids "$INSTANCE_ID"
 
-          aws ssm send-command \
+            echo "Wait for the instance to stop"
+            aws ec2 wait instance-stopped --instance-ids "$INSTANCE_ID"
+
+            echo "Start the instance"
+            aws ec2 start-instances --instance-ids "$INSTANCE_ID"
+
+            echo "Wait for the instance to fully start"
+            aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
+            
+            echo "Waiting for SSM agent to be ready..."
+            SSM_READY=false
+            for i in {1..30}; do
+              STATUS=$(aws ssm describe-instance-information --filters "Key=InstanceIds,Values=$INSTANCE_ID" --query 'InstanceInformationList[0].PingStatus' --output text)
+              if [[ "$STATUS" == "Online" ]]; then
+                SSM_READY=true
+                break
+              fi
+              echo "SSM not ready yet... waiting (attempt $i)"
+              sleep 15
+            done
+
+            if [[ "$SSM_READY" == "false" ]]; then
+              echo "SSM agent is not ready. Triggering SNS notification."
+              aws sns publish \
+                --topic-arn $SNS_TOPIC \
+                --subject "SSM Not Ready for Instance $INSTANCE_ID" \
+                --message "SSM agent did not become ready after EC2 start in "${{ github.event.inputs.environment }}" . Please investigate."
+              exit 1
+            fi
+
+            # Check instance status, fail and trigger SNS if not running
+            INSTANCE_STATE=$(aws ec2 describe-instance-status --instance-ids "$INSTANCE_ID" --query 'InstanceStatuses[0].InstanceState.Name' --output text)
+            if [[ "$INSTANCE_STATE" != "running" ]]; then
+              echo "Instance $INSTANCE_ID failed to start. Triggering SNS notification."
+              aws sns publish \
+                --topic-arn $SNS_TOPIC \
+                --subject "EC2 Start Failure for Instance $INSTANCE_ID" \
+                --message "Instance $INSTANCE_ID failed to start after "${{ github.event.inputs.environment }}" patching. Please investigate."
+              exit 1
+            fi
+                         
+
+            aws ssm send-command \
             --instance-ids "$INSTANCE_TO_PATCH" \
             --document-name "AWS-RunShellScript" \
             --comment "Backup /etc/httpd/conf.d, then restart Jira and HTTPD services" \
             --parameters 'commands=["sudo cp -r /etc/httpd/conf.d /etc/httpd/conf.d.bak", "sudo service httpd restart", "sudo service jira restart"]'
 
+            aws autoscaling exit-standby \
+              --auto-scaling-group-name "${{ env.ASG_NAME }}" \
+              --instance-ids "$INSTANCE_ID"
 
-          aws autoscaling exit-standby \
-            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
-            --instance-ids "$INSTANCE_TO_PATCH"
+            sleep 600
 
-           sleep 600
-
-          # Check node status using the API
-          NODE_STATUS=$(curl -X GET \
+            # Check node status using the API
+            NODE_STATUS=$(curl -X GET \
             -H "Authorization: Bearer ${{ env.TOKEN }}" \
             -H "Content-Type: application/json" \
             "${{ env.URL }}/rest/api/2/cluster/nodes" | jq .)
 
-          INSTANCE_TO_PATCH_PRIVATE_IP=$(aws ec2 describe-instances \
-            --instance-ids ${INSTANCE_IDS_ARRAY[0]} \
-            --query 'Reservations[].Instances[].PrivateIpAddress' \
-            --output text)
+            INSTANCE_PRIVATE_IP=$(aws ec2 describe-instances \
+              --instance-ids "$INSTANCE_ID" \
+              --query 'Reservations[].Instances[].PrivateIpAddress' \
+              --output text)
 
-            echo "Private IP: $INSTANCE_TO_PATCH_PRIVATE_IP"
+            echo "Private IP: $INSTANCE_PRIVATE_IP"
             echo "NODE_STATUS: $NODE_STATUS"
             
-          INSTANCE_ALIVE=$(echo "$NODE_STATUS" | jq --arg ip "$INSTANCE_TO_PATCH_PRIVATE_IP" '.[] | select(.nodeId == $ip and .state == "ACTIVE")')
-          echo "INSTANCE_ALIVE: $INSTANCE_ALIVE"
-          if [[ -n "$INSTANCE_ALIVE" ]]; then
-            echo "Instance ${INSTANCE_IDS_ARRAY[0]} is alive and healthy."
-            echo "patch-instance-1=success" >> $GITHUB_ENV
-          else
-            echo "Error: Instance ${INSTANCE_IDS_ARRAY[0]} is NOT healthy. Sending notification."
-  
-            aws sns publish \
-              --topic-arn ${{ env.SNS_TOPIC }} \
-              --subject "${{ env.SUBJECT_PREFIX }} Failed on Node $INSTANCE_TO_PATCH_PRIVATE_IP" \
-              --message "Patching of instance ${INSTANCE_IDS_ARRAY[0]} ($INSTANCE_TO_PATCH_PRIVATE_IP) failed. Please investigate."
+            INSTANCE_ALIVE=$(echo "$NODE_STATUS" | jq --arg ip "$INSTANCE_PRIVATE_IP" '.nodes[] | select(.nodeId == $ip and .state == "ACTIVE")')
+            if [[ -n "$INSTANCE_ALIVE" ]]; then
+              echo "Instance $INSTANCE_ID is alive and healthy."
+              echo "========================================================="
+            else
+              echo "Error: Instance $INSTANCE_ID is NOT healthy. Sending notification."  
+              aws sns publish \
+                --topic-arn ${{ env.SNS_TOPIC }} \
+                --subject "${{ env.SUBJECT_PREFIX }} Failed on Node $INSTANCE_PRIVATE_IP" \
+                --message "Patching of instance $INSTANCE_ID ($INSTANCE_PRIVATE_IP) failed. Please investigate."
+                
+              PATCH_SUCCESS=false  
+              break  
+            fi
+          done
 
-             echo "patch-instance-1=failure" >> $GITHUB_ENV
-            exit 1 
-          fi  
-
-      - name: Patch Instance 2
-        id: patch-instance-2
-        if: env.patch-instance-1 == 'success'
-        run: |
-          INSTANCE_IDS_ARRAY=(${{ env.INSTANCE_IDS }})
-          INSTANCE_TO_PATCH=${INSTANCE_IDS_ARRAY[1]}
-          echo "Patching instance: $INSTANCE_TO_PATCH"
-
-          aws autoscaling enter-standby \
-            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --should-decrement-desired-capacity
-         
-          aws ssm send-command \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Stop Jira and HTTPD services" \
-            --parameters 'commands=["sudo service httpd stop", "sudo service jira stop"]'
-            
-          aws ssm send-command \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Upgrade to latest Amazon Linux release" \
-            --parameters 'commands=["dnf -y --releasever=latest update"]'
-
-          aws ssm send-command \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Reboot EC2 instance" \
-            --parameters 'commands=["sudo reboot"]'
-         
-          sleep 120
-
-          aws ssm send-command \
-            --instance-ids "$INSTANCE_TO_PATCH" \
-            --document-name "AWS-RunShellScript" \
-            --comment "Backup /etc/httpd/conf.d, then restart Jira and HTTPD services" \
-            --parameters 'commands=["sudo cp -r /etc/httpd/conf.d /etc/httpd/conf.d.bak", "sudo service httpd restart", "sudo service jira restart"]'
-          
-
-          aws autoscaling exit-standby \
-            --auto-scaling-group-name "${{ env.ASG_NAME }}" \
-            --instance-ids "$INSTANCE_TO_PATCH"
-
-          sleep 600 
-
-          # Check node status using the API
-          NODE_STATUS=$(curl -X GET \
-            -H "Authorization: Bearer ${{ env.TOKEN }}" \
-            -H "Content-Type: application/json" \
-            "${{ env.URL }}/rest/api/2/cluster/nodes" | jq .)
-
-          INSTANCE_TO_PATCH_PRIVATE_IP=$(aws ec2 describe-instances --instance-ids ${INSTANCE_IDS_ARRAY[1]} --query 'Reservations[*].Instances[*].PrivateIpAddress' --output text)
-          echo "NODE_STATUS: $NODE_STATUS"
-          echo "Private IP: $INSTANCE_TO_PATCH_PRIVATE_IP"
-          INSTANCE_ALIVE=$(echo "$NODE_STATUS" | jq --arg ip "$INSTANCE_TO_PATCH_PRIVATE_IP" '.[] | select(.nodeId == $ip and .state == "ACTIVE")')
-  
-          if [[ -n "$INSTANCE_ALIVE" ]]; then
-            echo "Instance ${INSTANCE_IDS_ARRAY[1]} is alive and healthy."
-          else
-            echo "Error: Instance ${INSTANCE_IDS_ARRAY[1]} is NOT healthy. Sending notification."
-  
-            aws sns publish \
-              --topic-arn ${{ env.SNS_TOPIC }} \
-              --subject "${{ env.SUBJECT_PREFIX }} Failed on Node $INSTANCE_TO_PATCH_PRIVATE_IP" \
-              --message "Patching of instance ${INSTANCE_IDS_ARRAY[1]}($INSTANCE_TO_PATCH_PRIVATE_IP) failed. Please investigate."
-  
-            exit 2 
+          # Stop further patching if any instance failed
+          if [[ "$PATCH_SUCCESS" == "false" ]]; then
+            echo "Instances $INSTANCE_ID ($INSTANCE_PRIVATE_IP) failed the patching process. Exiting workflow."
+            exit 1
           fi
 
       - name: Set Auto Scaling Group to 2-2
