Update Jira_Patching.yml to enhance command execution

diff --git a/.github/workflows/Jira_Patching.yml b/.github/workflows/Jira_Patching.yml
--- a/.github/workflows/Jira_Patching.yml
+++ b/.github/workflows/Jira_Patching.yml
@@ -231,17 +231,45 @@ jobs:
               exit 1
             fi
 
+            echo "ds_agent tasks"
+              aws ssm send-command \
+                --instance-ids "$INSTANCE_ID" \
+                --document-name "AWS-RunShellScript" \
+                --comment "Stop ds_agent, remove dsa_filt, and start ds_agent" \
+                --parameters 'commands=["service ds_agent stop", "sleep 180", "sudo rmmod dsa_filter", "service ds_agent start"]' \
+                --query 'Command.CommandId' --output text > command-id.txt
+              COMMAND_ID=$(cat command-id.txt)
+              echo "Waiting for command to complete..."
+              for i in {1..30}; do
+                COMMAND_STATUS=$(aws ssm list-commands --command-id "$COMMAND_ID" --query 'Commands[0].Status' --output text)
+                echo "Current command status: $COMMAND_STATUS"
+                
+                if [[ "$COMMAND_STATUS" == "Success" ]]; then
+                  echo "Command completed successfully."
+                  break
+                elif [[ "$COMMAND_STATUS" == "Failed" ]]; then
+                  echo "Command failed. Exiting..."
+                  exit 1
+                fi
+                
+                sleep 30  
+              done  
+
             aws ssm send-command \
               --instance-ids "$INSTANCE_ID" \
               --document-name "AWS-RunShellScript" \
               --comment "Backup /etc/httpd/conf.d, then restart Jira and HTTPD services" \
-              --parameters 'commands=["sudo cp -r /etc/httpd/conf.d /etc/httpd/conf.d.bak", "sudo service httpd restart", "sudo service jira restart"]'
+              --parameters 'commands=["sudo cp -r /etc/httpd/conf.d /etc/httpd/conf.d.bak-$(date +%Y%m%d-%H%M%S)", "sudo service httpd restart", "sudo service jira restart"]'
 
             aws autoscaling exit-standby \
               --auto-scaling-group-name "${{ env.ASG_NAME }}" \
               --instance-ids "$INSTANCE_ID"
 
-            sleep 600
+            echo "Waiting 600 seconds to allow services and cluster to stabilize..."
+            for i in {1..10}; do
+              echo "  ... waiting $((i*60)) seconds elapsed"
+              sleep 60
+            done
 
             echo "Check node status using the API"
             NODE_STATUS=$(curl -s -X GET \
